# Generated by Django 4.2.5 on 2023-09-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='imgURL',
            field=models.TextField(default=''),
        ),
    ]
