# Generated by Django 4.2.5 on 2023-09-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audioURL',
            field=models.TextField(default=''),
        ),
    ]
